name: scheduled-build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push development image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: convenia/php:8.1-development

        # name: Build and push production image
        # uses: docker/build-push-action@v2
        # with:
        #   context: .
        #   push: true
        #   tags: convenia/php:8.1-development
